### 搜索${moduleName}
GET http://{{host}}:{{port}}/${camelModules}/search?page=0&size=10
Accept: application/json
Content-Type: application/json;charset=UTF-8
Authorization: {{auth_token}}

### 获取${moduleName}
GET http://{{host}}:{{port}}/${camelModules}/1
Accept: application/json
Content-Type: application/json;charset=UTF-8
Authorization: {{auth_token}}

### 添加${moduleName}
POST http://{{host}}:{{port}}/${camelModules}
Accept: application/json
Content-Type: application/json;charset=UTF-8
Authorization: {{auth_token}}

{
  <#list fields as field>
  "${field.camelName}": <#if field.isNumber || field.isBoolean>${field.defaultValue}<#else>"${field.defaultValue}"</#if><#if field_has_next>,</#if>
  </#list>
}

### 编辑${moduleName}
PUT http://{{host}}:{{port}}/${camelModules}/1
Accept: application/json
Content-Type: application/json;charset=UTF-8
Authorization: {{auth_token}}

{
  <#list fields as field>
  "${field.camelName}": <#if field.isNumber || field.isBoolean>${field.defaultValue}<#else>"${field.defaultValue}"</#if><#if field_has_next>,</#if>
  </#list>
}

### 删除${moduleName}
DELETE http://{{host}}:{{port}}/${camelModules}/1
Accept: application/json
Content-Type: application/json;charset=UTF-8
Authorization: {{auth_token}}
